### ISSUE TITLE
.whiteness turns white to red

### ISSUE THREAD

**Issue by mwinche** [MoOx/color#73]
In my node REPL (color@0.10.1, node@4.2.1):

```
[temp (master)]$ node
> var Color = require('color');
undefined
> new Color('#ffffff').whiteness(5).hexString()
'#FF0D0D'
> 
```

That doesn't seem right to me.

**Comment by MoOx** [comment]
To be honest I cannot confirm this bug. We should find a reference somewhere.

**Comment by Qix-** [comment]
This is correct functionality.

`.whiteness()` and its sister method `.blackness()` are part of the [HWB color model](http://fettblog.eu/hwb-colors/), which include Hue, Whiteness, and Blackness.

In short, hue defaults to 0&deg;, or red. The `.whiteness()` and `.blackness()` methods work on a 0-100 scale, so setting it to `5` takes most of the white out of the red, so to speak, making it very very close to `FF0000` - in fact, `0xFF * 0.05 == 0x0D`, hence `0xFF0D0D`.

Hope this helps!

**Comment by MoOx** [comment]
Thanks for this great explanation 👌🏼

**Comment by mwinche** [comment]
Indeed, great explanation! I guess I'm using the wrong tool for the job.

**Comment by Qix-** [comment]
@mwinche what are you trying to achieve?

**Comment by mwinche** [comment]
Basically, trying to take a color and make it 5% "whiter". Specifically, using it within cssnext:

```
box-shadow: color(var(--accent) whiteness(5%)) 0px 1px 1px 0px inset;
```

When the accent happened to be white or off-white it was doing a red box-shadow, which was not what I intended. Traced it all the way down to this color module.

**Comment by mwinche** [comment]
Playing around some more, looks like what I needed was this:

```
box-shadow: color(var(--accent) lightness(+5%)) 0px 1px 1px 0px inset;
```

Regardless, .whiteness turning white to red still felt weird, hence the issue.

**Comment by Qix-** [comment]
Yep I believe you're looking for `.lighten()` from this package. Usually when grayscale colors go to a reddish tint, it's a sign that you're working with a Hue-based model. :+1:

**Comment by mwinche** [comment]
Thanks for the tip!

**Comment by dfcreative** [comment]
@mwinche `.whiteness(5)` should be understood as 'take the [basic](http://www.w3.org/TR/css3-color/#html4) pure most saturated color and turn it's whiteness to 5%'. In case of `#fff` it is impossible to infer which color is the basic one, because it can be any. By default it is red (hue = 0⁰). Hope it makes any sense)

**Comment by mwinche** [comment]
Yeah, maybe I should take some time and learn all these color models, seems interesting. I'm sure HWB wouldn't exist if there wasn't some use case for which it was ideally suited.

**Comment by Qix-** [comment]
HWB was invented by the guy who invented HSL and HSV iirc. HWB is supposed to be more user-friendly. I'd have to agree. It's just not used very much.
